#ifndef CONFIG_H
#define CONFIG_H

#define ENABLE_MACHINE_LEARNING false // Dishwasher learn actions time using
#define ALLOW_SHUTDOWN_AFTER_START_S 4
#define BOOL_SENSORS_MIN_DETECT_VALUE 500
#define ENABLE_SENSORS_DEBUG false
#define SENSORS_DEBUG_INTERVAL_MS 1000
#define SENSORS_READ_INTERVAL_MS 100
#define MAX_REALISTIC_TEMPERATURE 100
#define MIN_REALISTIC_TEMPERATURE 0
#define ENABLE_ACTIONS_DEBUG true
#define ACTION_SOAPDOOR_WAIT 2 // seconds
#define MAX_ALLOWED_TIME_ADD_WATER 10 // seconds
#define MAX_ALLOWED_TIME_HEAT_WATER 10 // seconds
#define WATER_EMPTY_PUMP_TIME 10 // seconds

#endif