#ifndef IMAGES_H
#define IMAGES_H

// Text positions
#define POS_TEXT_CENTER 0
#define POS_TEXT_CENTER_BOTTOM 1

// Image positions 

// Circle positions 
#define POS_CIRCLE_BG_RIGHT_TOP 5

#define POS_CIRCLE_ICON_RIGHT_TOP_ONE 0

#define POS_CIRCLE_ICON_RIGHT_TOP_TWO_1 7
#define POS_CIRCLE_ICON_RIGHT_TOP_TWO_2 6

#define POS_CIRCLE_ICON_RIGHT_TOP_TREE_1 8
#define POS_CIRCLE_ICON_RIGHT_TOP_TREE_2 0
#define POS_CIRCLE_ICON_RIGHT_TOP_TREE_3 9

#define POS_CIRCLE_ICON_RIGHT_TOP_FOUR_1 10
#define POS_CIRCLE_ICON_RIGHT_TOP_FOUR_2 11
#define POS_CIRCLE_ICON_RIGHT_TOP_FOUR_3 12
#define POS_CIRCLE_ICON_RIGHT_TOP_FOUR_4 13

#define POS_CIRCLE_RIGHT_BOTTOM 4

#define POS_CIRCLE_ICON_RIGHT_BOTTOM_TWO_1 25
#define POS_CIRCLE_ICON_RIGHT_BOTTOM_TWO_2 24

#define POS_CIRCLE_ICON_RIGHT_BOTTOM_TREE_1 27
#define POS_CIRCLE_ICON_RIGHT_BOTTOM_TREE_2 23
#define POS_CIRCLE_ICON_RIGHT_BOTTOM_TREE_3 26

#define POS_CIRCLE_ICON_RIGHT_BOTTOM_FOUR_1 28
#define POS_CIRCLE_ICON_RIGHT_BOTTOM_FOUR_2 29
#define POS_CIRCLE_ICON_RIGHT_BOTTOM_FOUR_3 30
#define POS_CIRCLE_ICON_RIGHT_BOTTOM_FOUR_4 31

#define POS_CIRCLE_LEFT_BOTTOM 3

#define POS_CIRCLE_ICON_LEFT_BOTTOM_TWO_1 33
#define POS_CIRCLE_ICON_LEFT_BOTTOM_TWO_2 34

#define POS_CIRCLE_ICON_LEFT_BOTTOM_TREE_1 36
#define POS_CIRCLE_ICON_LEFT_BOTTOM_TREE_2 32
#define POS_CIRCLE_ICON_LEFT_BOTTOM_TREE_3 35

#define POS_CIRCLE_ICON_LEFT_BOTTOM_FOUR_1 37
#define POS_CIRCLE_ICON_LEFT_BOTTOM_FOUR_2 38
#define POS_CIRCLE_ICON_LEFT_BOTTOM_FOUR_3 39
#define POS_CIRCLE_ICON_LEFT_BOTTOM_FOUR_4 40

#define POS_CIRCLE_BG_LEFT_TOP 2

#define POS_CIRCLE_ICON_LEFT_TOP_ONE 0

#define POS_CIRCLE_ICON_LEFT_TOP_TWO_1 7
#define POS_CIRCLE_ICON_LEFT_TOP_TWO_2 6

#define POS_CIRCLE_ICON_LEFT_TOP_TREE_1 8
#define POS_CIRCLE_ICON_LEFT_TOP_TREE_2 0
#define POS_CIRCLE_ICON_LEFT_TOP_TREE_3 9

#define POS_CIRCLE_ICON_LEFT_TOP_FOUR_1 10
#define POS_CIRCLE_ICON_LEFT_TOP_FOUR_2 11
#define POS_CIRCLE_ICON_LEFT_TOP_FOUR_3 12
#define POS_CIRCLE_ICON_LEFT_TOP_FOUR_4 13

#define POS_CENTER_ICON 1

// Background images

// Circle right top
#define IMG_RIGHT_TOP_EMPTY 62

#define IMG_RIGHT_TOP_ONE 60
#define IMG_RIGHT_TOP_ONE_SELECTED 61

#define IMG_RIGHT_TOP_TWO 48
#define IMG_RIGHT_TOP_TWO_1_SELECTED 49
#define IMG_RIGHT_TOP_TWO_2_SELECTED 50

#define IMG_RIGHT_TOP_THREE 51
#define IMG_RIGHT_TOP_THREE_1_SELECTED 52
#define IMG_RIGHT_TOP_THREE_2_SELECTED 53
#define IMG_RIGHT_TOP_THREE_3_SELECTED 54

#define IMG_RIGHT_TOP_FOUR 55
#define IMG_RIGHT_TOP_FOUR_1_SELECTED 56
#define IMG_RIGHT_TOP_FOUR_2_SELECTED 57
#define IMG_RIGHT_TOP_FOUR_3_SELECTED 58
#define IMG_RIGHT_TOP_FOUR_4_SELECTED 59

// Circle right bottom
#define IMG_RIGHT_BOTTOM_EMPTY 63

#define IMG_RIGHT_BOTTOM_ONE 46
#define IMG_RIGHT_BOTTOM_ONE_SELECTED 47

#define IMG_RIGHT_BOTTOM_TWO 34
#define IMG_RIGHT_BOTTOM_TWO_1_SELECTED 35
#define IMG_RIGHT_BOTTOM_TWO_2_SELECTED 36

#define IMG_RIGHT_BOTTOM_THREE 37
#define IMG_RIGHT_BOTTOM_THREE_1_SELECTED 38
#define IMG_RIGHT_BOTTOM_THREE_2_SELECTED 39
#define IMG_RIGHT_BOTTOM_THREE_3_SELECTED 40

#define IMG_RIGHT_BOTTOM_FOUR 41
#define IMG_RIGHT_BOTTOM_FOUR_1_SELECTED 42
#define IMG_RIGHT_BOTTOM_FOUR_2_SELECTED 43
#define IMG_RIGHT_BOTTOM_FOUR_3_SELECTED 44
#define IMG_RIGHT_BOTTOM_FOUR_4_SELECTED 45

// Circle left bottom
#define IMG_LEFT_BOTTOM_EMPTY 64

#define IMG_LEFT_BOTTOM_ONE 32
#define IMG_LEFT_BOTTOM_ONE_SELECTED 33 

#define IMG_RLEFT_BOTTOM_TWO 20
#define IMG_LEFT_BOTTOM_TWO_1_SELECTED 21
#define IMG_LEFT_BOTTOM_TWO_2_SELECTED 22

#define IMG_LEFT_BOTTOM_THREE 23
#define IMG_LEFT_BOTTOM_THREE_1_SELECTED 24
#define IMG_LEFT_BOTTOM_THREE_2_SELECTED 25
#define IMG_LEFT_BOTTOM_THREE_3_SELECTED 26

#define IMG_LEFT_BOTTOM_FOUR 27
#define IMG_LEFT_BOTTOM_FOUR_1_SELECTED 28
#define IMG_LEFT_BOTTOM_FOUR_2_SELECTED 29
#define IMG_LEFT_BOTTOM_FOUR_3_SELECTED 30
#define IMG_LEFT_BOTTOM_FOUR_4_SELECTED 31

// Circle left top
#define IMG_LEFT_TOP_EMPTY 65

#define IMG_LEFT_TOP_ONE 18
#define IMG_LEFT_TOP_ONE_SELECTED 19

#define IMG_RLEFT_TOP_TWO 6
#define IMG_LEFT_TOP_TWO_1_SELECTED 7
#define IMG_LEFT_TOP_TWO_2_SELECTED 8

#define IMG_LEFT_TOP_THREE 9
#define IMG_LEFT_TOP_THREE_1_SELECTED 10
#define IMG_LEFT_TOP_THREE_2_SELECTED 11
#define IMG_LEFT_TOP_THREE_3_SELECTED 12

#define IMG_LEFT_TOP_FOUR 13
#define IMG_LEFT_TOP_FOUR_1_SELECTED 14
#define IMG_LEFT_TOP_FOUR_2_SELECTED 15
#define IMG_LEFT_TOP_FOUR_3_SELECTED 16
#define IMG_LEFT_TOP_FOUR_4_SELECTED 17

#endif